### ISSUE TITLE
Invalid value for shared scalar

### ISSUE THREAD

**Issue by SamCT** [oushujun/LTR_retriever#153]
Hello,

I'm trying the new install of LTR_retriever (2.9.4), and am getting an error, related to issue #104 :

```
Invalid value for shared scalar at /nfsX/LAB/usr/conda/LTR/LTR_retriever/bin/LTR.identifier.pl line 114, <ANNO> line 2048.
Thu May 11 09:16:46 PDT 2023    Intact LTR-RT found: 0
```

And in the error file of the SGE_Batch:
```
Invalid value for shared scalar at /nfsX/LAB/usr/conda/LTR/LTR_retriever/bin/LTR.identifier.pl line 114, <ANNO> line 2048.
cp: cannot stat 'genome.fasta.retriever.scn.adj': No such file or directory
```
This error is the same whether I am using the conda env install, or a manual install with pathways specified in the paths file.
Goal here was just to test whether the new version of retriever had a significant difference in LAI (I expect probably not?, but am curious). 

I get a successful run on the old version of LTR_retriever (2.9.0). To be clear I am following the pipeline specified in this github (suffixerator -> harvest -> LTR_paralellize -> *genome.fa.rawLTR.scn -> LTR_retriever). Tried rerunning the pipeline fresh to see if it was an issue related to old files and that doesn't seem to be related.

How might I be able to resolve this error and move forward with testing the new version of LTR_retriever?

Thank you

**Comment by oushujun** [comment]
That's a weird error (I don't remember I see this error before). Checked line 114 and there is only one variable: `$scn{$id}[12]`, which is the 13th column of the `*genome.fa.rawLTR.scn` file. You may want to check the scn file and see if there's any abnormality. If you can invoke the new LTR_retriever, that means the installation is good. Issue #104 seems to be not related. Did you check the program with the small test file?

Shujun

**Comment by SamCT** [comment]
By small test file, do you mean the dummb060817.fa within the database folder? I've tried that -- says no candidate is found (for both v2.9.0 and 2.9.4). For both instances the "Dependency checking: ALL passed!". Not sure if this is the correct test you are referring to.

And I think the .scn file is okay, considering I was able to properly generate an LAI index using LTR_retriever 2.9.0. Just finished another run successfully last night with that version. 

Here is the first 4 lines of my *genome.fa.rawLTR.scn file (I'm actually not seeing a 13th column?):

```95513  97730  2218  95513  95793  281  97459  97730  272  85.77  0
192080  202500  10421  192080  192399  320  202166  202500  335  88.96  0
309366  311693  2328  309366  309939  574  311106  311693  588  96.77  0
432534  440037  7504  432534  434109  1576  438458  440037  1580  97.85  0```

**Comment by oushujun** [comment]
There's  link to a small file in #104

**Comment by SamCT** [comment]
Running with the test genome.fa within the EDTA test files and I have the same issue using LRT_retriever version 2.9.4:

`gt suffixerator -db genome.fa -indexname genome.fa -tis -suf -lcp -des -ssp -sds -dna
gt ltrharvest -index genome.fa -minlenltr 100 -maxlenltr 7000 -mintsd 4 -maxtsd 6 -motif TGCA -motifmis 1 -similar 85 -vic 10 -seed 20 -seqids yes > test.fa.harvest.scn
LTR_FINDER_parallel -seq genome.fa -harvest_out -size 1000000 -time 300
cat genome.fa.harvest.scn genome.fa.finder.combine.scn > genome.fa.rawLTR.scn
LTR_retriever -genome genome.fa -inharvest genome.fa.rawLTR.scn
`

Sun May 14 05:14:58 PDT 2023    Dependency checking: All passed!
Sun May 14 05:15:12 PDT 2023    LTR_retriever is starting from the Init step.
Sun May 14 05:15:12 PDT 2023    Start to convert inputs...
                                Total candidates: 12
                                Total uniq candidates: 12

Sun May 14 05:15:12 PDT 2023    Module 1: Start to clean up candidates...
                                Sequences with 10 missing bp or 0.8 missing data rate will be discarded.
                                Sequences containing tandem repeats will be discarded.

Sun May 14 05:15:12 PDT 2023    12 clean candidates remained

Sun May 14 05:15:12 PDT 2023    Modules 2-5: Start to analyze the structure of candidates...
                                The terminal motif, TSD, boundary, orientation, age, and superfamily will be identified in this step.

/your_path_to/LTR_retriever -genome genome.fa -inharvest genome.fa.rawLTR.scn^[[A^[[B^[[BInvalid value for shared scalar at /nfs4/HORT/Vining_Lab/Users/talbots/bin/EDTA/share/LTR_retriever/bin/LTR.identifier.pl line 114, <ANNO> line 11.
Sun May 14 05:15:31 PDT 2023    Intact LTR-RT found: 0

cp: cannot stat 'genome.fa.retriever.scn.adj': No such file or directory
Sun May 14 05:15:31 PDT 2023    No LTR-RT was found in your data.

**Comment by ricardo-aaron** [comment]
I'm having the same issue with v2.9.4, tried two genomes, both output this:
Parameters: -genome genome_clean.fasta -inharvest genome.rawLTR.scn -threads 24 -noanno
Mon 19 Jun 2023 08:57:56 AM CDT Dependency checking: All passed!
Mon 19 Jun 2023 08:58:01 AM CDT LTR_retriever is starting from the Init step.
Mon 19 Jun 2023 08:58:03 AM CDT Start to convert inputs...
                                Total candidates: 599
                                Total uniq candidates: 558
Mon 19 Jun 2023 08:58:04 AM CDT Module 1: Start to clean up candidates...
                                Sequences with 10 missing bp or 0.8 missing data rate will be discarded.
                                Sequences containing tandem repeats will be discarded.
Mon 19 Jun 2023 08:58:05 AM CDT 558 clean candidates remained
Mon 19 Jun 2023 08:58:05 AM CDT Modules 2-5: Start to analyze the structure of candidates...
                                The terminal motif, TSD, boundary, orientation, age, and superfamily will be identified in this step.
Invalid value for shared scalar at /castle/rchavez/micromamba/envs/ltr_retriever/share/LTR_retriever/bin/LTR.identifier.pl line 114, <ANNO> line 88.
Mon 19 Jun 2023 08:58:29 AM CDT Intact LTR-RT found: 0
cp: cannot stat 'genome_clean.fasta.retriever.scn.adj': No such file or directory
Mon 19 Jun 2023 08:58:29 AM CDT No LTR-RT was found in your data.
Mon 19 Jun 2023 08:58:29 AM CDT All analyses were finished!

**Comment by oushujun** [comment]
Yeah there is a bug in v2. 9. 4,  You may use the v2. 9. 0 for now.

shujun

**Comment by oushujun** [comment]
Hello all,

This bug should be fixed in the latest version. Please update and run again. Let me know if you still have the issue.

Thanks!
Shujun

**Comment by SamCT** [comment]
Fixed! Thank you Shujun!

**Comment by XylonLeung** [comment]
> Hello all,
> 
> This bug should be fixed in the latest version. Please update and run again. Let me know if you still have the issue.
> 
> Thanks! Shujun

Hi Dr.Shujun, so much thanks for writing this fascinating program!

I've noticed that the `Invalid value` bug of LTR_retriever v2.9.4 is still presenting nowadays while I installed EDTA via conda and downgrading the version of LTR_retriever from 2.9.4 to 2.9.0 helps to fix this issue indeed.

Best,
Yanyang.

**Comment by oushujun** [comment]
Hi yangyang,

The latest version is 2.9.9. https://anaconda.org/bioconda/ltr_retriever

THanks,
SHujun
